name: Test
on: [workflow_dispatch]
        
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:   
      - name: Say hello
        uses: Torodde/Basta23Bootcamp/@v1
        with:
          who-to-greet: '@torodde'
